In [ ]:
# 入力データの取得

from pathlib import Path
import os

print(os.getcwd())

ALL_DATA = sorted(Path("./input").iterdir())
ARTICLE_PATH, CUSTOMERS_PATH, SAMPLE_SUBMISSION_PATH, TRANSAC_PATH = ALL_DATA

/Users/kurokawa/Desktop/hobby/data_analysis/kaggle/h_and_m

In [ ]:
import polars as pl

articles_df = pl.read_csv(ARTICLE_PATH)  # (105_542, 25)
custom_df = pl.read_csv(CUSTOMERS_PATH)  # (105_542, 25)
sample_sub_df = pl.read_csv(SAMPLE_SUBMISSION_PATH)  # (1, 7)
transac_df = pl.read_csv(TRANSAC_PATH)  # このデータが重いから注意(31_788_324, 5)

In [12]:
# 取引データ
print(transac_df.schema)
print(transac_df.null_count())
transac_df.head()

Schema({'t_dat': String, 'customer_id': String, 'article_id': Int64, 'price': Float64, 'sales_channel_id': Int64})
shape: (1, 5)
┌───────┬─────────────┬────────────┬───────┬──────────────────┐
│ t_dat ┆ customer_id ┆ article_id ┆ price ┆ sales_channel_id │
│ ---   ┆ ---         ┆ ---        ┆ ---   ┆ ---              │
│ u32   ┆ u32         ┆ u32        ┆ u32   ┆ u32              │
╞═══════╪═════════════╪════════════╪═══════╪══════════════════╡
│ 0     ┆ 0           ┆ 0          ┆ 0     ┆ 0                │
└───────┴─────────────┴────────────┴───────┴──────────────────┘

shape: (5, 5)
┌────────────┬─────────────────────────────────┬────────────┬──────────┬──────────────────┐
│ t_dat      ┆ customer_id                     ┆ article_id ┆ price    ┆ sales_channel_id │
│ ---        ┆ ---                             ┆ ---        ┆ ---      ┆ ---              │
│ str        ┆ str                             ┆ i64        ┆ f64      ┆ i64              │
╞════════════╪═════════════════════════════════╪════════════╪══════════╪══════════════════╡
│ 2018-09-20 ┆ 000058a12d5b43e67d225668fa1f8d… ┆ 663713001  ┆ 0.050831 ┆ 2                │
│ 2018-09-20 ┆ 000058a12d5b43e67d225668fa1f8d… ┆ 541518023  ┆ 0.030492 ┆ 2                │
│ 2018-09-20 ┆ 00007d2de826758b65a93dd24ce629… ┆ 505221004  ┆ 0.015237 ┆ 2                │
│ 2018-09-20 ┆ 00007d2de826758b65a93dd24ce629… ┆ 685687003  ┆ 0.016932 ┆ 2                │
│ 2018-09-20 ┆ 00007d2de826758b65a93dd24ce629… ┆ 685687004  ┆ 0.016932 ┆ 2                │
└────────────┴─────────────────────────────────┴────────────┴──────────┴──────────────────┘

In [16]:
# 商品データ
pl.Config.set_tbl_cols(-1)

print(articles_df.schema)
print(articles_df.null_count())
articles_df.head()

Schema({'article_id': Int64, 'product_code': Int64, 'prod_name': String, 'product_type_no': Int64, 'product_type_name': String, 'product_group_name': String, 'graphical_appearance_no': Int64, 'graphical_appearance_name': String, 'colour_group_code': Int64, 'colour_group_name': String, 'perceived_colour_value_id': Int64, 'perceived_colour_value_name': String, 'perceived_colour_master_id': Int64, 'perceived_colour_master_name': String, 'department_no': Int64, 'department_name': String, 'index_code': String, 'index_name': String, 'index_group_no': Int64, 'index_group_name': String, 'section_no': Int64, 'section_name': String, 'garment_group_no': Int64, 'garment_group_name': String, 'detail_desc': String})
shape: (1, 25)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ art ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ gra ┆ gra ┆ col ┆ col ┆ per ┆ per ┆ per ┆ per ┆ dep ┆ dep ┆ ind ┆ ind ┆ ind ┆ ind ┆ sec ┆ sec ┆ gar ┆ gar ┆ det │
│ icl ┆ duc ┆ d_n ┆ duc ┆ duc ┆ duc ┆ phi ┆ phi ┆ our ┆ our ┆ cei ┆ cei ┆ cei ┆ cei ┆ art ┆ art ┆ ex_ ┆ ex_ ┆ ex_ ┆ ex_ ┆ tio ┆ tio ┆ men ┆ men ┆ ail │
│ e_i ┆ t_c ┆ ame ┆ t_t ┆ t_t ┆ t_g ┆ cal ┆ cal ┆ _gr ┆ _gr ┆ ved ┆ ved ┆ ved ┆ ved ┆ men ┆ men ┆ cod ┆ nam ┆ gro ┆ gro ┆ n_n ┆ n_n ┆ t_g ┆ t_g ┆ _de │
│ d   ┆ ode ┆ --- ┆ ype ┆ ype ┆ rou ┆ _ap ┆ _ap ┆ oup ┆ oup ┆ _co ┆ _co ┆ _co ┆ _co ┆ t_n ┆ t_n ┆ e   ┆ e   ┆ up_ ┆ up_ ┆ o   ┆ ame ┆ rou ┆ rou ┆ sc  │
│ --- ┆ --- ┆ u32 ┆ _no ┆ _na ┆ p_n ┆ pea ┆ pea ┆ _co ┆ _na ┆ lou ┆ lou ┆ lou ┆ lou ┆ o   ┆ ame ┆ --- ┆ --- ┆ no  ┆ nam ┆ --- ┆ --- ┆ p_n ┆ p_n ┆ --- │
│ u32 ┆ u32 ┆     ┆ --- ┆ me  ┆ ame ┆ ran ┆ ran ┆ de  ┆ me  ┆ r_v ┆ r_v ┆ r_m ┆ r_m ┆ --- ┆ --- ┆ u32 ┆ u32 ┆ --- ┆ e   ┆ u32 ┆ u32 ┆ o   ┆ ame ┆ u32 │
│     ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆ ce_ ┆ ce_ ┆ --- ┆ --- ┆ alu ┆ alu ┆ ast ┆ ast ┆ u32 ┆ u32 ┆     ┆     ┆ u32 ┆ --- ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ no  ┆ nam ┆ u32 ┆ u32 ┆ e_i ┆ e_n ┆ er_ ┆ er_ ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆ u32 ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆     ┆     ┆ d   ┆ ame ┆ id  ┆ nam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 416 │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

shape: (5, 25)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ art ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ gra ┆ gra ┆ col ┆ col ┆ per ┆ per ┆ per ┆ per ┆ dep ┆ dep ┆ ind ┆ ind ┆ ind ┆ ind ┆ sec ┆ sec ┆ gar ┆ gar ┆ det │
│ icl ┆ duc ┆ d_n ┆ duc ┆ duc ┆ duc ┆ phi ┆ phi ┆ our ┆ our ┆ cei ┆ cei ┆ cei ┆ cei ┆ art ┆ art ┆ ex_ ┆ ex_ ┆ ex_ ┆ ex_ ┆ tio ┆ tio ┆ men ┆ men ┆ ail │
│ e_i ┆ t_c ┆ ame ┆ t_t ┆ t_t ┆ t_g ┆ cal ┆ cal ┆ _gr ┆ _gr ┆ ved ┆ ved ┆ ved ┆ ved ┆ men ┆ men ┆ cod ┆ nam ┆ gro ┆ gro ┆ n_n ┆ n_n ┆ t_g ┆ t_g ┆ _de │
│ d   ┆ ode ┆ --- ┆ ype ┆ ype ┆ rou ┆ _ap ┆ _ap ┆ oup ┆ oup ┆ _co ┆ _co ┆ _co ┆ _co ┆ t_n ┆ t_n ┆ e   ┆ e   ┆ up_ ┆ up_ ┆ o   ┆ ame ┆ rou ┆ rou ┆ sc  │
│ --- ┆ --- ┆ str ┆ _no ┆ _na ┆ p_n ┆ pea ┆ pea ┆ _co ┆ _na ┆ lou ┆ lou ┆ lou ┆ lou ┆ o   ┆ ame ┆ --- ┆ --- ┆ no  ┆ nam ┆ --- ┆ --- ┆ p_n ┆ p_n ┆ --- │
│ i64 ┆ i64 ┆     ┆ --- ┆ me  ┆ ame ┆ ran ┆ ran ┆ de  ┆ me  ┆ r_v ┆ r_v ┆ r_m ┆ r_m ┆ --- ┆ --- ┆ str ┆ str ┆ --- ┆ e   ┆ i64 ┆ str ┆ o   ┆ ame ┆ str │
│     ┆     ┆     ┆ i64 ┆ --- ┆ --- ┆ ce_ ┆ ce_ ┆ --- ┆ --- ┆ alu ┆ alu ┆ ast ┆ ast ┆ i64 ┆ str ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆ no  ┆ nam ┆ i64 ┆ str ┆ e_i ┆ e_n ┆ er_ ┆ er_ ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ i64 ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆     ┆     ┆ d   ┆ ame ┆ id  ┆ nam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ i64 ┆ str ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 108 ┆ 108 ┆ Str ┆ 253 ┆ Ves ┆ Gar ┆ 101 ┆ Sol ┆ 9   ┆ Bla ┆ 4   ┆ Dar ┆ 5   ┆ Bla ┆ 167 ┆ Jer ┆ A   ┆ Lad ┆ 1   ┆ Lad ┆ 16  ┆ Wom ┆ 100 ┆ Jer ┆ Jer │
│ 775 ┆ 775 ┆ ap  ┆     ┆ t   ┆ men ┆ 001 ┆ id  ┆     ┆ ck  ┆     ┆ k   ┆     ┆ ck  ┆ 6   ┆ sey ┆     ┆ ies ┆     ┆ ies ┆     ┆ ens ┆ 2   ┆ sey ┆ sey │
│ 015 ┆     ┆ top ┆     ┆ top ┆ t   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆ wea ┆     ┆ wea ┆     ┆ Eve ┆     ┆ Bas ┆ top │
│     ┆     ┆     ┆     ┆     ┆ Upp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆ r   ┆     ┆ r   ┆     ┆ ryd ┆     ┆ ic  ┆ wit │
│     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ay  ┆     ┆     ┆ h   │
│     ┆     ┆     ┆     ┆     ┆ bod ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆     ┆ nar │
│     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ics ┆     ┆     ┆ row │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uld │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  │
│ 108 ┆ 108 ┆ Str ┆ 253 ┆ Ves ┆ Gar ┆ 101 ┆ Sol ┆ 10  ┆ Whi ┆ 3   ┆ Lig ┆ 9   ┆ Whi ┆ 167 ┆ Jer ┆ A   ┆ Lad ┆ 1   ┆ Lad ┆ 16  ┆ Wom ┆ 100 ┆ Jer ┆ Jer │
│ 775 ┆ 775 ┆ ap  ┆     ┆ t   ┆ men ┆ 001 ┆ id  ┆     ┆ te  ┆     ┆ ht  ┆     ┆ te  ┆ 6   ┆ sey ┆     ┆ ies ┆     ┆ ies ┆     ┆ ens ┆ 2   ┆ sey ┆ sey │
│ 044 ┆     ┆ top ┆     ┆ top ┆ t   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆ wea ┆     ┆ wea ┆     ┆ Eve ┆     ┆ Bas ┆ top │
│     ┆     ┆     ┆     ┆     ┆ Upp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆ r   ┆     ┆ r   ┆     ┆ ryd ┆     ┆ ic  ┆ wit │
│     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ay  ┆     ┆     ┆ h   │
│     ┆     ┆     ┆     ┆     ┆ bod ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆     ┆ nar │
│     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ics ┆     ┆     ┆ row │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uld │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  │
│ 108 ┆ 108 ┆ Str ┆ 253 ┆ Ves ┆ Gar ┆ 101 ┆ Str ┆ 11  ┆ Off ┆ 1   ┆ Dus ┆ 9   ┆ Whi ┆ 167 ┆ Jer ┆ A   ┆ Lad ┆ 1   ┆ Lad ┆ 16  ┆ Wom ┆ 100 ┆ Jer ┆ Jer │
│ 775 ┆ 775 ┆ ap  ┆     ┆ t   ┆ men ┆ 001 ┆ ipe ┆     ┆ Whi ┆     ┆ ty  ┆     ┆ te  ┆ 6   ┆ sey ┆     ┆ ies ┆     ┆ ies ┆     ┆ ens ┆ 2   ┆ sey ┆ sey │
│ 051 ┆     ┆ top ┆     ┆ top ┆ t   ┆ 7   ┆     ┆     ┆ te  ┆     ┆ Lig ┆     ┆     ┆     ┆ Bas ┆     ┆ wea ┆     ┆ wea ┆     ┆ Eve ┆     ┆ Bas ┆ top │
│     ┆     ┆ (1) ┆     ┆     ┆ Upp ┆     ┆     ┆     ┆     ┆     ┆ ht  ┆     ┆     ┆     ┆ ic  ┆     ┆ r   ┆     ┆ r   ┆     ┆ ryd ┆     ┆ ic  ┆ wit │
│     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ay  ┆     ┆     ┆ h   │
│     ┆     ┆     ┆     ┆     ┆ bod ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆     ┆ nar │
│     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ics ┆     ┆     ┆ row │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uld │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e…  │
│ 110 ┆ 110 ┆ OP  ┆ 306 ┆ Bra ┆ Und ┆ 101 ┆ Sol ┆ 9   ┆ Bla ┆ 4   ┆ Dar ┆ 5   ┆ Bla ┆ 133 ┆ Cle ┆ B   ┆ Lin ┆ 1   ┆ Lad ┆ 61  ┆ Wom ┆ 101 ┆ Und ┆ Mic │
│ 065 ┆ 065 ┆ T-s ┆     ┆     ┆ erw ┆ 001 ┆ id  ┆     ┆ ck  ┆     ┆ k   ┆     ┆ ck  ┆ 9   ┆ an  ┆     ┆ ger ┆     ┆ ies ┆     ┆ ens ┆ 7   ┆ er- ┆ rof │
│ 001 ┆     ┆ hir ┆     ┆     ┆ ear ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆ ies ┆     ┆ wea ┆     ┆ Lin ┆     ┆ ,   ┆ ibr │
│     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ger ┆     ┆ /Ti ┆     ┆ r   ┆     ┆ ger ┆     ┆ Nig ┆ e   │
│     ┆     ┆ (Id ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ie  ┆     ┆ ght ┆     ┆     ┆     ┆ ie  ┆     ┆ htw ┆ T-s │
│     ┆     ┆ ro) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ ear ┆ hir │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bra │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ un… │
│ 110 ┆ 110 ┆ OP  ┆ 306 ┆ Bra ┆ Und ┆ 101 ┆ Sol ┆ 10  ┆ Whi ┆ 3   ┆ Lig ┆ 9   ┆ Whi ┆ 133 ┆ Cle ┆ B   ┆ Lin ┆ 1   ┆ Lad ┆ 61  ┆ Wom ┆ 101 ┆ Und ┆ Mic │
│ 065 ┆ 065 ┆ T-s ┆     ┆     ┆ erw ┆ 001 ┆ id  ┆     ┆ te  ┆     ┆ ht  ┆     ┆ te  ┆ 9   ┆ an  ┆     ┆ ger ┆     ┆ ies ┆     ┆ ens ┆ 7   ┆ er- ┆ rof │
│ 002 ┆     ┆ hir ┆     ┆     ┆ ear ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆ ies ┆     ┆ wea ┆     ┆ Lin ┆     ┆ ,   ┆ ibr │
│     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ger ┆     ┆ /Ti ┆     ┆ r   ┆     ┆ ger ┆     ┆ Nig ┆ e   │
│     ┆     ┆ (Id ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ie  ┆     ┆ ght ┆     ┆     ┆     ┆ ie  ┆     ┆ htw ┆ T-s │
│     ┆     ┆ ro) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ ear ┆ hir │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bra │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ un… │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [30]:
# 購入者データ
print(custom_df.schema)
print(custom_df.null_count())
custom_df.head()
print(len(custom_df))

Schema({'customer_id': String, 'FN': Float64, 'Active': Float64, 'club_member_status': String, 'fashion_news_frequency': String, 'age': Int64, 'postal_code': String})
shape: (1, 7)
┌─────────────┬────────┬────────┬────────────────────┬────────────────────────┬───────┬─────────────┐
│ customer_id ┆ FN     ┆ Active ┆ club_member_status ┆ fashion_news_frequency ┆ age   ┆ postal_code │
│ ---         ┆ ---    ┆ ---    ┆ ---                ┆ ---                    ┆ ---   ┆ ---         │
│ u32         ┆ u32    ┆ u32    ┆ u32                ┆ u32                    ┆ u32   ┆ u32         │
╞═════════════╪════════╪════════╪════════════════════╪════════════════════════╪═══════╪═════════════╡
│ 0           ┆ 895050 ┆ 907576 ┆ 6062               ┆ 16009                  ┆ 15861 ┆ 0           │
└─────────────┴────────┴────────┴────────────────────┴────────────────────────┴───────┴─────────────┘
1371980

In [17]:
# 提出データ
print(sample_sub_df.schema)
sample_sub_df.head()

Schema({'customer_id': String, 'prediction': String})

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ customer_id                     ┆ prediction                      │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ 00000dbacae5abe5e23885899a1fa4… ┆ 0706016001 0706016002 03728600… │
│ 0000423b00ade91418cceaf3b26c6a… ┆ 0706016001 0706016002 03728600… │
│ 000058a12d5b43e67d225668fa1f8d… ┆ 0706016001 0706016002 03728600… │
│ 00005ca1c9ed5f5146b52ac8639a40… ┆ 0706016001 0706016002 03728600… │
│ 00006413d8573cd20ed7128e53b7b1… ┆ 0706016001 0706016002 03728600… │
└─────────────────────────────────┴─────────────────────────────────┘

In [24]:
pl.Config.set_fmt_str_lengths(100000)

print(sample_sub_df.head(1)["prediction"])

shape: (1,)
Series: 'prediction' [str]
[
	"0706016001 0706016002 0372860001 0610776002 0759871002 0464297007 0372860002 0610776001 0399223001 0706016003 0720125001 0156231001"
]

In [28]:
contents = sample_sub_df.head(1)["prediction"].item()

print(len(contents.split()))
print(sample_sub_df.head(1)["prediction"].item())

12
0706016001 0706016002 0372860001 0610776002 0759871002 0464297007 0372860002 0610776001 0399223001 0706016003 0720125001 0156231001

# article.csv に関する分析

In [ ]:
# 離散型データの確認